version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    image: backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb_container:27017
volumes:
  mongodb_data:
