# Specifies the name of the workflow
name: Build on PR

#  Defines the event that triggers the workflow. Here, it is triggered on pull requests to the master branch.
on:
  pull_request:
    branches:
      - main
    paths:
      - "week 17/paytm/**"

# Contains the list of jobs to be executed in the workflow.
jobs:
  # Defines a job named "build".
  build:
    # Specifies the type of machine to run the job on, in this case, an Ubuntu-based runner.
    runs-on: ubuntu-latest

    # Lists the steps to be executed in the job.
    steps:
      # Checks out the repository code (Clone the repo on the machine).
      - uses: actions/checkout@v3

      # Sets up Node.js with the specified version.
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Installs the project dependencies.
      - name: Install dependencies
        run: npm install

      # It generates the Prisma client
      - name: Generate prisma client
        run: npm run db:generate

      # Runs the build script defined in the package.json file.
      - name: Run build
        run: npm run build
# 1. Commit and push the changes to the `master` branch of your forked repository.
# 2. Create a new branch with some minimal changes and create a PR from it to the `master` branch.
# 3. You should see the workflow run automatically when the PR is created. The build status will be displayed on the PR page.
