apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: REFUQUJBU0VfVVJMPSJwb3N0Z3Jlc3FsOi8vbXl1c2VyOm15cGFzc3dvcmRmcm9tc2VjcmV0QGxvY2FsaG9zdDo1NDMyIgpDQUNIRV9TSVpFPTEwClBBWU1FTlRfR0FURVdBWV9VUkw9ImFwaS5yYXpvcnBheS5jb20iCk1BWF9DQVJUPTIwClNFU1NJT05fVElNRU9VVD0zMDAw
